export const MAP_DATA_UPDATE = 'MAP_DATA_UPDATE';
export const MAP_DATA_LOADING = 'MAP_DATA_LOADING';
export const MAP_DATA_LOADING_COMPLETE = 'MAP_DATA_LOADING_COMPLETE';
export const MAP_DATA_LOADING_ERROR = 'MAP_DATA_LOADING_ERROR';
